title: SEAsia R36
url: https://github.com/NOC-MSM/SEAsia_R36/blob/main/docs/assets/SEAsoa_r36_logo.jpeg
description: "Instructions for setting up and running the SEAsia NEMO configuration in 1/36 degree resolution"
author: "Anna Katavouta"

theme: minima
