title: SEAsia R36
description: "Instructions for setting up and running the SEAsia NEMO configuration in 1/36 degree resolution"
author: "Anna Katavouta"

theme: just-the-docs
# Make sure your repository URL point to the website home, not a direct image file
url: "https://noc-msm.github.io/SEAsia_R36"
